//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlaMungo.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YesAlaMungoEntities : DbContext
    {
        public YesAlaMungoEntities()
            : base("name=YesAlaMungoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buy> Buys { get; set; }
        public virtual DbSet<BuyUsedBook> BuyUsedBooks { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<MetaDataBook> MetaDataBooks { get; set; }
        public virtual DbSet<Sell> Sells { get; set; }
        public virtual DbSet<SellUsedBook> SellUsedBooks { get; set; }
        public virtual DbSet<UsedBook> UsedBooks { get; set; }
    }
}
